/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package ContraseñaIgu;

import BaseDeDatos.BorrarBD;
import BaseDeDatos.BuscarBD;
import BaseDeDatos.BuscarContactos;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author EdUaRdO
 */
public class Buscar extends javax.swing.JFrame {

    /** Creates new form Buscar */
    public Buscar() {
        initComponents();
        setVisible(true);
        cargarAplicaciones();
    }
    public void cargarAplicaciones() {  
        BuscarContactos cc = new BuscarContactos();
        DefaultComboBoxModel modeloAplicacion = new DefaultComboBoxModel(cc.mostrarAplicacion());
        CBoxAplicaciones.setModel(modeloAplicacion);
    } 
    private String aplicacionMostrar;
    private String usuarioMostrar;
    private String contrasenaMostrar;
    private String Email_recuperacionMostrar;
    private String Correo_electronico_usuariosMostrar;
    
    public void llevarDatos(String aplicacion1,String usuario,String contrasena,String Email_recuperacion,String Correo_electronico_usuarios){
    this.aplicacionMostrar=aplicacion1;
    this.usuarioMostrar=usuario;
    this.contrasenaMostrar=contrasena;
    this.Email_recuperacionMostrar=Email_recuperacion;
    this.Correo_electronico_usuariosMostrar=Correo_electronico_usuarios;
    
    txtMostrar.setText("La Aplicacion "+ aplicacionMostrar + " El:"+"\n Usuario es: "+ usuarioMostrar +"\n Contraseña es: "+ contrasenaMostrar
    +"\n Email de recuperacion:"+ Email_recuperacionMostrar +"\n Email de Security In Your Password: "+ Correo_electronico_usuariosMostrar);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CBoxAplicaciones = new javax.swing.JComboBox<>();
        BotonBorrar = new javax.swing.JButton();
        BotonBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMostrar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(60, 9, 108));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Security In Your Password");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Aplicacion:");

        CBoxAplicaciones.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        CBoxAplicaciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBoxAplicacionesItemStateChanged(evt);
            }
        });

        BotonBorrar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        BotonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ContraseñaIguImagen/borrarG.png"))); // NOI18N
        BotonBorrar.setText("Borrar");
        BotonBorrar.setBorderPainted(false);
        BotonBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonBorrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ContraseñaIguImagen/borrarC.png"))); // NOI18N
        BotonBorrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ContraseñaIguImagen/borrarC.png"))); // NOI18N
        BotonBorrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });

        BotonBuscar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        BotonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ContraseñaIguImagen/buscarG.png"))); // NOI18N
        BotonBuscar.setText("Buscar");
        BotonBuscar.setToolTipText("");
        BotonBuscar.setBorder(null);
        BotonBuscar.setContentAreaFilled(false);
        BotonBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ContraseñaIguImagen/buscarC.png"))); // NOI18N
        BotonBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ContraseñaIguImagen/buscarC.png"))); // NOI18N
        BotonBuscar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        txtMostrar.setColumns(20);
        txtMostrar.setRows(5);
        jScrollPane2.setViewportView(txtMostrar);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(BotonBuscar)
                        .addGap(90, 90, 90)
                        .addComponent(BotonBorrar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CBoxAplicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBoxAplicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonBuscar)
                    .addComponent(BotonBorrar))
                .addGap(176, 176, 176))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBoxAplicacionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBoxAplicacionesItemStateChanged

    }//GEN-LAST:event_CBoxAplicacionesItemStateChanged

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
    Object seleccion = CBoxAplicaciones.getSelectedItem();  
    
    // Verifica que la selección no sea nula  
    if (seleccion != null) {  
        // Verificamos si la selección es una instancia de BuscarContactos  
        if (seleccion instanceof BuscarContactos) {  
            BuscarContactos contacto = (BuscarContactos) seleccion;  
            String aplicacion = contacto.getNombre();  
            // Aquí realizar la búsqueda con el nombre de la aplicación  
            BuscarBD buscarAplicacion = new BuscarBD();  
            buscarAplicacion.aplicacion1(aplicacion, this);     
        } else {  
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una aplicación válida.", "Advertencia", JOptionPane.WARNING_MESSAGE);  
        }  
    } else {  
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una aplicación.", "Advertencia", JOptionPane.WARNING_MESSAGE);  
    } 
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed
     Object seleccion = CBoxAplicaciones.getSelectedItem();  

    
    // Verifica que la selección no sea nula  
    if (seleccion != null) {  
        // Verificamos si la selección es una instancia de BuscarContactos  
        if (seleccion instanceof BuscarContactos) {  
            BuscarContactos contacto = (BuscarContactos) seleccion;  
            String aplicacion = contacto.getNombre();  
            // Aquí realizar la búsqueda con el nombre de la aplicación  
            BorrarBD buscarAplicacion = new BorrarBD();  
            buscarAplicacion.eliContacto(aplicacion);     
        }   
    }  
    }//GEN-LAST:event_BotonBorrarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JComboBox<String> CBoxAplicaciones;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtMostrar;
    // End of variables declaration//GEN-END:variables

}
